apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server # server-deployment.yml
  ports:
    - port: 5000
      targetPort: 5000
  